import React from "react";
import Head from 'next/head'
import { Header } from '@/components/Header'
import { Data } from '../lib/data'
import { ListLinks } from "@/components/ListLinks";

export default function Home() {
  const { user } = Data
  return (
    <>
      <Head>
        <title>{user.fullname}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ListLinks />
    </>
  )
}
